### ISSUE TITLE
Docker-compose up failing

### ISSUE THREAD

**Issue by mickwilson** [opendatacube/geobase#30]
Ubuntu Mint 20.0
Brand new docker instance. No previous images or containers.

Mapx installed under /usr/local/src from zip downloaded 15 Sep 2020 and seems complete
(base) wilsonm@Asclepius:~/usrlocal/src/map-x-mgl$ ls 
api  app  build.sh  CHANGELOG.md  docker-compose.init.sh  docker-compose.yml  geoserver  LICENSE.md  mapx.dev.default_env  mapx.dev.env  pg  probe  readme.md  redis.conf  _shared  update_changelog.sh  version.txt

docker-compose pull runs to completion with some warnings but no fatal errors.
docker-compose up message log attached:

[20200918-mapx-start-log-MW.txt](https://github.com/opendatacube/geobase/files/5250786/20200918-mapx-start-log-MW.txt)

**Comment by Kirill888** [comment]
sorry, @mickwilson this report does not make any sense to me, this repo doesn't even have a docker compose file.
