### ISSUE TITLE
Starting Point Clarity

### ISSUE THREAD

**Issue by tushar10sh** [opendatacube/geobase#31]
Sorry for creating this but this is not an issue with code but I am having trouble with choosing starting point for jupyter notebook image.

I am trying to setup this kind of On-Premise [Architecture](https://drive.google.com/file/d/1sxgzlFkym_13i8P9fvEXXFCVbrv7yxxq/view?usp=sharing) but I am not able to get clarity on starting point for building a jupyter hub single user image based on geobase. There are various github repos ( datacube charts, odc-dev, cube-in-box, jupyerhub) and dockerhub images to choose from. Can someone help?
I am provisioning DBaaS so that user doesn't have to run system init repeatedly whenever the user containers get up and running after being culled down after inactivity. Also, user can shutdown complete container server without losing Db state. 
Any suggestions on improving above architecture are also welcomed.

Thanks in advance.

**Comment by Kirill888** [comment]
This is where we maintain jupyterlab docker image:

https://github.com/GeoscienceAustralia/dea-sandbox

**Comment by woodcockr** [comment]
Stale
