### ISSUE TITLE
Failing to build docker image due numexpr3 installation.

### ISSUE THREAD

**Issue by tushar10sh** [opendatacube/geobase#32]
https://github.com/opendatacube/geobase/blob/2ed7a24861f88706f95ea76f52413aa342a655ed/odc/odc-dev/conf/requirements.txt#L52

Since the current version of numexpr3 is 3.0.1a5. This line when executed fails the docker image build process. If the version is changed to previous pre-release version i.e. `pip install numexpr3==3.0.1a1` installation continues. 

Some change can be made if validity of this issue checks out.

Also, why & where numexpr3 is needed given that numexpr is already installed ?

**Comment by Kirill888** [comment]
@tushar10sh this is provided as an example only, it worked at some point in time, python dependencies are always changing we can not afford to keep these examples up-to-date.

For a better maintained deployment you should look here: https://github.com/GeoscienceAustralia/dea-sandbox
