### ISSUE TITLE
Most recent pip no longer supports constraints with pre-compiled wheels

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/geobase#45]
We are using `pip --constraints ` to make sure that some pre-compiled geo libraries are used instead of binary version from pypi. This feature has been removed from latest version of `pip>=20.3`.

`pip` does not provide reasonable mechanisms for using cached locally compiled wheels. One can use `--no-binary=pyproj` to force installation of `pyproj` from source, but this ALWAYS compiles a fresh copy and that behaviour is by design (I have asked).

So, `env-build-tool` needs to be redesigned to work around those implementation constraints of `pip`.

As a short term measure we can freeze pip at `20.2.*` version for now, this requires updating lines like these:

https://github.com/opendatacube/geobase/blob/08454271629404e03ab9a45129c04a75c7e1aa67/base/wheels/env-build-tool#L49

https://github.com/opendatacube/geobase/blob/08454271629404e03ab9a45129c04a75c7e1aa67/base/wheels/env-build-tool#L72

https://github.com/opendatacube/geobase/blob/08454271629404e03ab9a45129c04a75c7e1aa67/base/wheels/env-build-tool#L95

to have `pip==20.2.4` instead.

**Comment by woodcockr** [comment]
hi ODC folks,

I was just looking into the status of this issue and checking to see if I might be able to fix it whilst I'm doing some other build related work. I noticed the reference to [datacube-core PR 1051](https://github.com/opendatacube/datacube-core/pull/1051/files).

Is that approach the intended fix for this issue in which case why isn't it part of geobase? 

Just trying to get my head around the ecosystem before looking at possible fixes.

**Comment by Kirill888** [comment]
I feel like approach in a linked PR is the way to go, except it's a bit more complicated than what is usually needed, as above is building a python environment such that it has all the dependencies of datacube but not datacube itself. If all you have instead is a `requirements.txt` and `constraints.txt` then things are way simpler.

I have come to realize that this whole `:wheels` layer was a mistake, and having pre-compiled wheels is not worth the trouble. We should get rid of that layer and instead provide templates for building wheelhouse from `requirements.txt+constraints.txt` in an incremental fashion while providing suggestion for which libraries

- need compiling (rasterio, shapely, pyproj, pygdal, netcdf, h5py, and more)
- worth compiling (yaml, zstandard, hdstats, .)
- better installed in binary mode (scipy, matplotlib, tensorflow)

**Comment by woodcockr** [comment]
FYI I have a new build operating this way based off the geobase-3.1.3 builder image. It's out in beta form in our EASI Hubs but so far seems to be working fine. The GA fc library had to be removed due to builds failing with numpy 1.19.5 which we require for our tensorflow support. It looks like the error is common to a lot of libraries and is an upstream change in numpy imports. I may revisit this later and see if I can diagnose it better and/or supply a fix but other priorities are currently in play.

I believe we should commit to this change in approach and make decisions on PRs #50 and #51 and which would in turn close out this issue.

**Comment by Kirill888** [comment]
This is now fixed, we no longer pre-compile any wheels, but we do force compilation of important geo libraries so long as one uses `env-build-tool` utilities.
