### ISSUE TITLE
Consider removing "pandana" due to restrictive AGPL license

### ISSUE THREAD

**Issue by mpaget** [opendatacube/geobase#61]
[Pandana](https://github.com/UDST/pandana) has an AGPL license, which is quite restrictive and might be in conflict with (the intent of) Apache. See https://choosealicense.com/licenses.

Thanks to @benjaminleighton for alerting the CSIRO crew to this. We've removed pandana from our geobase+ builds with no adverse affects (yet... :) ).

A code search and dependency check suggests that pandana isn't required in ODC (nor DEA, DEAfrica from a cursory look).

This issue mostly flags it with you to do your own checks, please.

**Comment by Kirill888** [comment]
@mpaget did you mean to raise this issue in sandbox repo?

base images do NOT include any python libs, pre-compiled wheels no longer happen, and pandana was not part of those I don't think

edit: missed NOT

**Comment by Kirill888** [comment]
Or do you mean this one:

https://github.com/opendatacube/geobase/blob/3b9546335923d33cfdfd5f9a0e93031da696296a/odc/odc-dev/conf/requirements.txt#L73

we can remove that for sure.

it's really just an example docker, I don't think anyone uses it, not even sure if it builds to be honest

**Comment by mpaget** [comment]
Yes, that's the only place it occurs in this repo, and in the corresponding `constraints.txt`.

I suspect there may be a history across other builds that have picked up pandana in their `requirements.txt`'s, possibly initially copied from here.

Your recent updates to this repo will flow through. I guess we're just flagging it here so it can be addressed elsewhere as and when appropriate.

**Comment by Kirill888** [comment]
removed
