### ISSUE TITLE
Vulnerability and staleness

### ISSUE THREAD

**Issue by benjimin** [opendatacube/geobase#71]
Issues relating to this repo becoming stale:
* Scheduled CVE scans were automatically disabled (for repo inactivity)
* The current images do contain a recently found `libc` vulnerability (requiring update here before any downstream projects can pass their own scans)
* Reporting step (for scan failures) is broken. The slack notification attempt errors 404.
* Perhaps there should be a prominent deprecation warning if this image base is no longer maintained, or at least some explanatory notes if it is no longer recommended for particular uses.

See [Builder scan fail](https://github.com/opendatacube/geobase/actions/runs/1689761361) and [Runner scan fail](https://github.com/opendatacube/geobase/actions/runs/1689762164)

**Comment by woodcockr** [comment]
Good point though some folks are still using it, including me, so far as I can tell:
https://github.com/GeoscienceAustralia/dea-sandbox/blob/develop/docker/Dockerfile

Though I have downstream image builds which fix a few of things you mention.

Be worth raising this at an upcoming ODC Steering Committee meeting to get a resolution to your final point.
